name: Pull Request Workflow

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    
concurrency:
  group: pr-pipeline-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  testRunner:
    name: Test âœ¨
    runs-on: ubuntu-8-cores
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Run tests
        uses: game-ci/unity-test-runner@v4
        id: testRunner
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          checkName: ${{ matrix.testMode }} test results
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          gitPrivateToken: ${{ secrets.TOKEN_ACCESS_UNITY_PACKAGES }}
          unityVersion: "2022.3.17f1"

      - uses: actions/upload-artifact@v4
        with:
          name: Test results
          path: ${{ steps.testRunner.outputs.artifactsPath }}
